[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/Api"
  to = "https://app.ecofleet.com/seeme/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
